### ISSUE TITLE
There were some problems reproducing these projects.

### ISSUE THREAD

**Issue by LDT-dream** [xvzcf/pq-tls-benchmark#3]
I use a docker image which is download by 
`docker pull ubuntu:18.04`

and then Downloaded some of the software needed for this project.
`apt-get install dialog  vim curl  iproute2 git ethtool sudo systemctl python3 doxygen apt-utils inetutils-ping`

then Downloaded this Github project by
`git clone https://github.com/xvzcf/pq-tls-benchmark.git`
In the system path of \home.

`cd /home/pq-tls-benchmark/emulation-exp/code`
then run `./install-prereqs-ubuntu.sh` to nitializes the system environment , It's working.

and then I  `cd kex` and run ./setup.sh followed by python3 experiment.py.
there is a error appear like this 
![image](https://user-images.githubusercontent.com/46264010/91552205-00edbf00-e95e-11ea-8453-881c2c4acba1.png)

The program still runs and ends in ten minutes.

**But The output data is very different from yours!**
![image](https://user-images.githubusercontent.com/46264010/91552359-427e6a00-e95e-11ea-9bd6-01bbaf6b7f62.png)

The output result contains one column missing and the data is incorrect！

I don't know what's wrong.Can you look at this for me?
I couldn’t have done it without you.  It's been bothering me for a long time ! I’m very grateful.

**Comment by LDT-dream** [comment]
I know what the problem is. There's nothing wrong with that.To get the same data as the paper, I need to modify the parameters in the experiment.py file.

**Comment by xvzcf** [comment]
Apologies for the delay in getting back to you, but glad to hear you got the experiment running.

As for the data, I've uploaded the dataset that was used in the most recent version of the paper. Hope this helps.
