### ISSUE TITLE
Emulation experiment README link clarification

### ISSUE THREAD

**Issue by gz101** [xvzcf/pq-tls-benchmark#6]
I'm trying to run this code on an Apple M1 chip device which doesn't support the required extensions. I'm just wondering if the line to be changed to pull the latest liboqs version should be in the [install script](https://github.com/xvzcf/pq-tls-benchmark/blob/d8387e7c5ba4ae7fed32ac6bf2dcb1ba9521d95e/emulation-exp/code/install-prereqs-ubuntu.sh#L25), rather than the one below that prints the available extensions?

https://github.com/xvzcf/pq-tls-benchmark/blob/d8387e7c5ba4ae7fed32ac6bf2dcb1ba9521d95e/emulation-exp/code/README.md?plain=1#L16

**Comment by xvzcf** [comment]
Apologies for the late reply, I was travelling. But yes, I haven't worked on liboqs for some time now, and I don't really have the wherewithal for updates to this repository.
